### ISSUE TITLE
Can't seem to load the extension at all... "vscode is not defined"

### ISSUE THREAD

**Issue by armchairdeity** [dasdeck/do#1]
Issue Type: <b>Bug</b>

Start up VS Code
Activate Developer Tools
Click the Console tab
Observe the following error message re "vscode not defined":
>ERR vscode is not defined: ReferenceError: vscode is not defined
	at Object.eval (eval at eval (C:\Users\a80fbzz\.vscode\extensions\jmanuels.do-0.0.8\out\Do.js:95:22), &lt;anonymous&gt;:4:13)
	at ActionDispatcher.eval (C:\Users\a80fbzz\.vscode\extensions\jmanuels.do-0.0.8\out\Do.js:98:23)
	at ActionDispatcher.dispatchActionObject (C:\Users\a80fbzz\.vscode\extensions\jmanuels.do-0.0.8\out\Do.js:201:22)
	at ActionDispatcher.dispatchObject (C:\Users\a80fbzz\.vscode\extensions\jmanuels.do-0.0.8\out\Do.js:118:18)
	at ActionDispatcher.dispatchAction (C:\Users\a80fbzz\.vscode\extensions\jmanuels.do-0.0.8\out\Do.js:73:22)
	at __dirname.dispatchAcionList.list.forEach.jobs.push.done (C:\Users\a80fbzz\.vscode\extensions\jmanuels.do-0.0.8\out\Do.js:107:36)
	at C:\Users\a80fbzz\.vscode\extensions\jmanuels.do-0.0.8\node_modules\async\dist\async.js:3853:24
	at replenish (C:\Users\a80fbzz\.vscode\extensions\jmanuels.do-0.0.8\node_modules\async\dist\async.js:946:17)
	at C:\Users\a80fbzz\.vscode\extensions\jmanuels.do-0.0.8\node_modules\async\dist\async.js:950:9
	at eachOfLimit (C:\Users\a80fbzz\.vscode\extensions\jmanuels.do-0.0.8\node_modules\async\dist\async.js:975:24)
	at C:\Users\a80fbzz\.vscode\extensions\jmanuels.do-0.0.8\node_modules\async\dist\async.js:980:16
	at _parallel (C:\Users\a80fbzz\.vscode\extensions\jmanuels.do-0.0.8\node_modules\async\dist\async.js:3852:5)
	at Object.series (C:\Users\a80fbzz\.vscode\extensions\jmanuels.do-0.0.8\node_modules\async\dist\async.js:4708:5)
	at ActionDispatcher.dispatchAcionList (C:\Users\a80fbzz\.vscode\extensions\jmanuels.do-0.0.8\out\Do.js:114:25)
	at ActionDispatcher.dispatchAction (C:\Users\a80fbzz\.vscode\extensions\jmanuels.do-0.0.8\out\Do.js:57:22)
	at __dirname.dispatchAction.result.loadCommands (C:\Users\a80fbzz\.vscode\extensions\jmanuels.do-0.0.8\out\Do.js:52:22)
	at __dirname.loadCommands.vscode.commands.getCommands.then.newAllCommands (C:\Users\a80fbzz\.vscode\extensions\jmanuels.do-0.0.8\out\Do.js:227:17)
at &lt;anonymous&gt;

Extension version: 0.0.8
VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|47.38GB (32.49GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by armchairdeity** [comment]
Ping? Anyone?
